### ISSUE TITLE
🔧 [FIX] 경기 캘린더 화면의 응답 모델을 이전에 사용했던 모델로 변경

### ISSUE THREAD

**Issue by yooonji08** [Team-Safezone/Safezone-iOS#41]
## 🐞 About Issue
- 경기 캘린더 화면에서 사용하는 응답 모델을 새로운 응답 모델로 바꿔놨었음.
- 그러나 서버에서 아직 변경된 응답 모델의 반영이 되지 않았기 때문에, 서버 통신 시 오류가 발생함

## 💫 Branch Name
SF-88/fix/#41-Server-MatchCalendar-Model-Restore

## 📋 To do
- [x] 응답 모델 변경(새로운 모델 -> 이전 모델)

**Comment by daeun127** [comment]
수고했어요~
